[project]
name = "makeghrepo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ben Shore", email = "01.amusing_cozies@icloud.com" }
]
requires-python = ">=3.14"
dependencies = [
    "copier>=9.18.2",
    "gitpython>=3.1.62",
]

[project.scripts]
makeghrepo = "makeghrepo:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.9",
    "typer>=0.27.2",
]
